// AUTO-GENERATED — DO NOT EDIT MANUALLY
// Run: node scripts/gen_question_audio.cjs to regenerate

export const audioMap = {
  "Oliver's toy shop just received a huge delivery! There are four hundred and seventy-six blocks on the shelf, and three hundred and fifty-seven more just arrived. Can you help Leo count them all without losing track?": "/assets/audio/audio_02bf26dae2b4.mp3",
  "Oliver packed three hundred and sixty-four biscuits in the morning. Ruby packed two hundred and seventy-five more in the afternoon. They wanted to find out how many biscuits they had altogether!": "/assets/audio/audio_7c95365c4491.mp3",
  "Let's line them up in columns. Hundreds, Tens, and Ones. Start from the ones.": "/assets/audio/audio_2f739855bdfd.mp3",
  "Six tens plus seven tens equals thirteen tens! That is more than nine, so we need to regroup. We trade ten tens for one hundred and carry it to the hundreds column.": "/assets/audio/audio_5ec0f8896f73.mp3",
  "Three hundreds plus two hundreds plus one more equals six hundreds. The answer is six hundred and thirty-nine! Oliver and Ruby have six hundred and thirty-nine biscuits!": "/assets/audio/audio_59f2132b9681.mp3",
  "Ruby had seven hundred and thirty-two biscuits ready to ship. She needed to send four hundred and sixty-eight of them. How many would she have left?": "/assets/audio/audio_9c76bdb2537d.mp3",
  "Two ones minus eight ones — we cannot do that! We need to borrow a ten from the tens column. Now we have twelve ones. Twelve minus eight equals four ones.": "/assets/audio/audio_e9b4d8535628.mp3",
  "After lending one ten, we only have two tens left. Two tens minus six tens — we cannot do that either! We borrow one hundred from the hundreds column. Now we have twelve tens. Twelve tens minus six tens equals six tens.": "/assets/audio/audio_69c85edeba6b.mp3",
  "Six hundreds, minus one hundred we lent, minus four hundreds equals two hundreds. So seven hundred and thirty-two minus four hundred and sixty-eight equals two hundred and sixty-four. Ruby has two hundred and sixty-four biscuits left!": "/assets/audio/audio_e3bcf7f8bf72.mp3",
  "Drag the hundreds, tens, and ones blocks into the columns. Watch what happens when a column has more than nine!": "/assets/audio/audio_23f18511b530.mp3",
  "Whoa! Too many ones — time to regroup! Watch ten ones snap into one ten rod.": "/assets/audio/audio_0c043bf34ebc.mp3",
  "Amazing! Ten tens just became one hundred. Your regrouping is perfect!": "/assets/audio/audio_8f76f695f2b0.mp3",
  "Now let's try borrowing. When the ones column does not have enough, we borrow a ten from next door.": "/assets/audio/audio_c16307c3b3e2.mp3",
  "Great borrowing! Now type your answer in the column. Start from the ones.": "/assets/audio/audio_f5d56b77f485.mp3",
  "Brilliant regrouping! You are a hundreds hero!": "/assets/audio/audio_39efbf3bbf9d.mp3",
  "Almost! Check your regrouping in the tens column.": "/assets/audio/audio_c30dfe08a10d.mp3",
  "Let me show you the hint. Look at the column where you need to regroup.": "/assets/audio/audio_7f72e8d4a58b.mp3",
  "Well done! You just cracked a double regrouping problem!": "/assets/audio/audio_44f5fc7d661d.mp3",
  "Streak on fire! Five in a row — you are incredible!": "/assets/audio/audio_2a2777123487.mp3",
  "You have learned how to regroup hundreds today! Can you explain to Leo what regrouping means, and show him one example? Use numbers or draw it out!": "/assets/audio/audio_2646665690f0.mp3",
  "What is three hundred and sixty-four plus two hundred and seventy-five?": "/assets/audio/audio_q001_44aaa5bda1da.mp3",
  "What is four hundred and eighty-two plus three hundred and fifty-three?": "/assets/audio/audio_q002_312f59fb1ba3.mp3",
  "What is two hundred and ninety-one plus four hundred and sixty-three?": "/assets/audio/audio_q003_da6e83470661.mp3",
  "What is three hundred and seventy-two plus four hundred and fifty-one?": "/assets/audio/audio_q004_293f2382bceb.mp3",
  "What is one hundred and ninety-three plus five hundred and thirty-four?": "/assets/audio/audio_q005_f184cc0ed047.mp3",
  "What is five hundred and eighty-one plus two hundred and forty-two?": "/assets/audio/audio_q006_60202c62220b.mp3",
  "What is two hundred and sixty-three plus four hundred and seventy-two?": "/assets/audio/audio_q007_d4f6a4c3808e.mp3",
  "What is four hundred and ninety-four plus two hundred and thirty-one?": "/assets/audio/audio_q008_bb2f829204d5.mp3",
  "What is three hundred and seventy-five plus four hundred and eighty-three?": "/assets/audio/audio_q009_7705cbd680d8.mp3",
  "What is five hundred and ninety-two plus two hundred and seventy-one?": "/assets/audio/audio_q010_751cc63dc94c.mp3",
  "What is four hundred and eighty-six plus three hundred and fifty-seven?": "/assets/audio/audio_q011_fa6637b3dec5.mp3",
  "What is three hundred and seventy-eight plus two hundred and eighty-six?": "/assets/audio/audio_q012_2d311ab2e073.mp3",
  "What is two hundred and ninety-seven plus four hundred and eighty-five?": "/assets/audio/audio_q013_a49014842aca.mp3",
  "What is four hundred and fifty-nine plus two hundred and seventy-eight?": "/assets/audio/audio_q014_51362a9578af.mp3",
  "What is five hundred and sixty-eight plus two hundred and ninety-seven?": "/assets/audio/audio_q015_34a6b1cf06ab.mp3",
  "What is one hundred and eighty-seven plus five hundred and eighty-eight?": "/assets/audio/audio_q016_e8724693e73d.mp3",
  "What is two hundred and sixty-eight plus three hundred and seventy-nine?": "/assets/audio/audio_q017_a305a64b2a57.mp3",
  "What is three hundred and ninety-five plus two hundred and sixty-seven?": "/assets/audio/audio_q018_6c37caaca472.mp3",
  "What is four hundred and seventy-nine plus one hundred and eighty-five?": "/assets/audio/audio_q019_70ab3f90e02f.mp3",
  "What is two hundred and eighty-four plus three hundred and ninety-eight?": "/assets/audio/audio_q020_d643eeb80476.mp3",
  "What is seven hundred and thirty-two minus four hundred and sixty-two?": "/assets/audio/audio_q021_b88c56be04b8.mp3",
  "What is six hundred and twenty-four minus two hundred and fifty-one?": "/assets/audio/audio_q022_61c56be20501.mp3",
  "What is eight hundred and fifteen minus three hundred and forty-two?": "/assets/audio/audio_q023_bc30469e9ac8.mp3",
  "What is five hundred and thirty-seven minus two hundred and eighty-four?": "/assets/audio/audio_q024_5b8bfe311d5d.mp3",
  "What is nine hundred and eighteen minus four hundred and seventy-three?": "/assets/audio/audio_q025_6b953e06d0d8.mp3",
  "What is six hundred and forty-nine minus two hundred and eighty-two?": "/assets/audio/audio_q026_1448bdefb086.mp3",
  "What is seven hundred and twenty-eight minus three hundred and fifty-six?": "/assets/audio/audio_q027_070f7df04136.mp3",
  "What is eight hundred and forty-five minus four hundred and ninety-one?": "/assets/audio/audio_q028_3b8a1fa089ec.mp3",
  "What is five hundred and sixteen minus two hundred and sixty-three?": "/assets/audio/audio_q029_1702f4c8ab9d.mp3",
  "What is seven hundred and thirty-nine minus four hundred and fifty-one?": "/assets/audio/audio_q030_fb935c6629e3.mp3",
  "What is seven hundred and twenty-three minus four hundred and sixty-eight?": "/assets/audio/audio_q031_bb25f9595933.mp3",
  "What is six hundred and twelve minus two hundred and seventy-eight?": "/assets/audio/audio_q032_ba0e12722e13.mp3",
  "What is eight hundred and thirty-four minus four hundred and seventy-nine?": "/assets/audio/audio_q033_e24da2f8dd24.mp3",
  "What is five hundred and twenty-one minus two hundred and eighty-five?": "/assets/audio/audio_q034_f8e6ecfa7b9a.mp3",
  "What is seven hundred and fifteen minus three hundred and sixty-eight?": "/assets/audio/audio_q035_66aff0d316cc.mp3",
  "What is six hundred and thirty-two minus two hundred and seventy-five?": "/assets/audio/audio_q036_4195f1f34422.mp3",
  "What is five hundred and twenty-four minus one hundred and eighty-nine?": "/assets/audio/audio_q037_112f1010b92b.mp3",
  "What is eight hundred and thirteen minus four hundred and fifty-seven?": "/assets/audio/audio_q038_d3570ee2d928.mp3",
  "What is eight hundred minus three hundred and fifty-six?": "/assets/audio/audio_q039_a32c34b8a490.mp3",
  "What is six hundred minus two hundred and forty-eight?": "/assets/audio/audio_q040_6052a6232934.mp3",
  "Look at the equation: 3 [?] 5 plus 2 [?] 8 equals 643. What are the missing tens digits?": "/assets/audio/audio_q041_d63581a3cae7.mp3",
  "Look at the equation: 4 [?] 6 plus 3 [?] 7 equals 843. What are the missing tens digits?": "/assets/audio/audio_q042_2224edf64afd.mp3",
  "Look at the equation: 2 [?] 7 plus 4 [?] 5 equals 782. What are the missing tens digits?": "/assets/audio/audio_q043_f9c92162f297.mp3",
  "Look at the equation: 5 [?] 3 plus 2 [?] 8 equals 841. What are the missing tens digits?": "/assets/audio/audio_q044_4446b95ee3e5.mp3",
  "Look at the equation: 1 [?] 2 plus 4 [?] 3 equals 635. What are the missing tens digits?": "/assets/audio/audio_q045_6bf4b01e9b41.mp3",
  "Look at the equation: 2 [?] 4 plus 3 [?] 9 equals 663. What are the missing tens digits?": "/assets/audio/audio_q046_68d9aea93443.mp3",
  "Look at the equation: 4 [?] 1 plus 1 [?] 3 equals 634. What are the missing tens digits?": "/assets/audio/audio_q047_26ac145eedab.mp3",
  "Look at the equation: 3 [?] 5 plus 2 [?] 7 equals 662. What are the missing tens digits?": "/assets/audio/audio_q048_c7dfe0943e17.mp3",
  "Look at the equation: 4 [?] 9 plus 1 [?] 5 equals 664. What are the missing tens digits?": "/assets/audio/audio_q049_9fec831ee6bf.mp3",
  "Look at the equation: 2 [?] 4 plus 3 [?] 8 equals 682. What are the missing tens digits?": "/assets/audio/audio_q050_edb78e72e2f9.mp3",
  "Oliver baked four hundred and seventy-five cookies in the morning. Ruby packed three hundred and forty-eight cookies in the afternoon. How many cookies did they have altogether?": "/assets/audio/audio_q051_cb441fb68d5a.mp3",
  "Emma collected three hundred and eighty-two stamps. James gave her two hundred and seventy-four more stamps. How many stamps does Emma have now?": "/assets/audio/audio_q052_52491b11c401.mp3",
  "Sophie folded two hundred and eighty-nine origami cranes. Daniel folded three hundred and seventy-four more cranes. How many origami cranes did they fold in total?": "/assets/audio/audio_q053_b931f699b8f7.mp3",
  "Leo stacked four hundred and fifty-six toy blocks. Charlotte stacked two hundred and eighty-seven blocks on top. How many blocks did they stack altogether?": "/assets/audio/audio_q054_d979ea69e17b.mp3",
  "Ethan bought five hundred and ninety-three crayons. Grace bought two hundred and forty-five crayons. How many crayons did they buy altogether?": "/assets/audio/audio_q055_166a53295215.mp3",
  "Oliver packed three hundred and sixty-seven biscuits in the morning. Ruby packed four hundred and seventy-eight biscuits. How many biscuits did they pack in total?": "/assets/audio/audio_q056_190ef7f3170a.mp3",
  "Emma had two hundred and seventy-six stickers. Sophie gave her three hundred and fifty-eight more stickers. How many stickers does Emma have in total?": "/assets/audio/audio_q057_894452e9ea1e.mp3",
  "James bought four hundred and eighty-nine postcards. Daniel bought three hundred and seventy-two postcards. How many postcards did they buy in total?": "/assets/audio/audio_q058_1c3f9888c588.mp3",
  "Charlotte folded five hundred and ninety-seven origami cranes. Grace folded two hundred and eighty-four cranes. How many did they fold altogether?": "/assets/audio/audio_q059_8a7166c98d32.mp3",
  "Ethan stacked three hundred and sixty-eight toy blocks. Leo stacked four hundred and seventy-nine toy blocks. How many blocks did they stack altogether?": "/assets/audio/audio_q060_ad7ec47cb8a3.mp3",
  "Emma had six hundred and twenty-four stickers. She gave two hundred and fifty-one stickers away to her friends. How many stickers did she have left?": "/assets/audio/audio_q061_e087999e0c99.mp3",
  "Ruby baked seven hundred and thirty-two biscuits. She shipped four hundred and sixty-two of them. How many biscuits are left in the bakery?": "/assets/audio/audio_q062_0f670431af45.mp3",
  "James collected eight hundred and thirty-four marbles. He lost four hundred and seventy-nine marbles. How many marbles does he have left?": "/assets/audio/audio_q063_bd21df1fc8c9.mp3",
  "Sophie borrowed seven hundred and fifteen library books for the school project. She returned three hundred and sixty-eight books. How many books does she still have?": "/assets/audio/audio_q064_1b2e3695244c.mp3",
  "Daniel had five hundred and twenty-one postcards. He sent two hundred and eighty-five of them. How many postcards are left?": "/assets/audio/audio_q065_5668cafd86f7.mp3",
  "Charlotte folded six hundred and thirty-two origami cranes. She gave away two hundred and seventy-five of them. How many cranes does she have now?": "/assets/audio/audio_q066_50c7e71c61fc.mp3",
  "Ethan had five hundred and twenty-four crayons. He gave one hundred and eighty-nine away. How many crayons does he have left?": "/assets/audio/audio_q067_8c4ccd8e00ae.mp3",
  "Grace bought eight hundred and thirteen stickers. She pasted four hundred and fifty-seven of them in her album. How many stickers are left?": "/assets/audio/audio_q068_c5679c8d1a1f.mp3",
  "Leo received a box of eight hundred toy blocks. He gave three hundred and fifty-six blocks to Oliver. How many blocks does Leo have left?": "/assets/audio/audio_q069_f722120b1d0f.mp3",
  "Sophie inflated six hundred balloons for the school carnival. Two hundred and forty-eight balloons popped. How many balloons are left?": "/assets/audio/audio_q070_4dcca0434786.mp3",
  "Is five hundred and sixty-three plus two hundred and seventy-eight equal to eight hundred and thirty-one? True or False?": "/assets/audio/audio_q071_0d316b97fe58.mp3",
  "Is four hundred and eighty-six plus three hundred and fifty-seven equal to eight hundred and forty-three? True or False?": "/assets/audio/audio_q072_6cab3d905fdf.mp3",
  "Is seven hundred and thirty-two minus four hundred and sixty-two equal to two hundred and seventy? True or False?": "/assets/audio/audio_q073_74c3337cb346.mp3",
  "Is eight hundred minus three hundred and fifty-six equal to five hundred and forty-four? True or False?": "/assets/audio/audio_q074_79c7c57bb248.mp3",
  "Is three hundred and eighty-two plus four hundred and fifty-three equal to eight hundred and thirty-five? True or False?": "/assets/audio/audio_q075_0c3a18d5f47c.mp3",
  "Is six hundred and twelve minus two hundred and seventy-eight equal to three hundred and forty-four? True or False?": "/assets/audio/audio_q076_49c2b9f4ad1b.mp3",
  "Is two hundred and ninety-seven plus four hundred and eighty-five equal to seven hundred and seventy-two? True or False?": "/assets/audio/audio_q077_72ccdeb12692.mp3",
  "Is seven hundred and twenty-three minus four hundred and sixty-eight equal to two hundred and fifty-five? True or False?": "/assets/audio/audio_q078_6d0a02633f5c.mp3",
  "Is four hundred and seventy-nine plus one hundred and eighty-five equal to six hundred and fifty-four? True or False?": "/assets/audio/audio_q079_c1517e36cd2f.mp3",
  "Is six hundred minus two hundred and forty-eight equal to three hundred and fifty-two? True or False?": "/assets/audio/audio_q080_bfedd61eda19.mp3",
  "If seven hundred and thirty-two minus four hundred and sixty-eight equals two hundred and sixty-four, then two hundred and sixty-four plus four hundred and sixty-eight equals what?": "/assets/audio/audio_q081_2c6f7ccd54d3.mp3",
  "If eight hundred minus three hundred and fifty-six equals four hundred and forty-four, then four hundred and forty-four plus three hundred and fifty-six equals what?": "/assets/audio/audio_q082_1309161f0885.mp3",
  "If six hundred and twelve minus two hundred and seventy-eight equals three hundred and thirty-four, then three hundred and thirty-four plus two hundred and seventy-eight equals what?": "/assets/audio/audio_q083_d4057a3fd6b8.mp3",
  "If eight hundred and thirty-four minus four hundred and seventy-nine equals three hundred and fifty-five, then three hundred and fifty-five plus four hundred and seventy-nine equals what?": "/assets/audio/audio_q084_fd9276457725.mp3",
  "If five hundred and twenty-one minus two hundred and eighty-five equals two hundred and thirty-six, then two hundred and thirty-six plus two hundred and eighty-five equals what?": "/assets/audio/audio_q085_79b401db4394.mp3",
  "If seven hundred and fifteen minus three hundred and sixty-eight equals three hundred and forty-seven, then three hundred and forty-seven plus three hundred and sixty-eight equals what?": "/assets/audio/audio_q086_0c8e862481f0.mp3",
  "If six hundred and thirty-two minus two hundred and seventy-five equals three hundred and fifty-seven, then three hundred and fifty-seven plus two hundred and seventy-five equals what?": "/assets/audio/audio_q087_f4506b6a7a2e.mp3",
  "If five hundred and twenty-four minus one hundred and eighty-nine equals three hundred and thirty-five, then three hundred and thirty-five plus one hundred and eighty-nine equals what?": "/assets/audio/audio_q088_0bc4f64b6795.mp3",
  "If eight hundred and thirteen minus four hundred and fifty-seven equals three hundred and fifty-six, then three hundred and fifty-six plus four hundred and fifty-seven equals what?": "/assets/audio/audio_q089_802d3ad64253.mp3",
  "If six hundred minus two hundred and forty-eight equals three hundred and fifty-two, then three hundred and fifty-two plus two hundred and forty-eight equals what?": "/assets/audio/audio_q090_89e711acd776.mp3",
  "What operation makes this correct? Five hundred and three, question mark, two hundred and ninety-eight equals eight hundred and one. Is it plus or minus?": "/assets/audio/audio_q091_6d1a959ac1e4.mp3",
  "What operation makes this correct? Eight hundred and one, question mark, five hundred and three equals two hundred and ninety-eight. Is it plus or minus?": "/assets/audio/audio_q092_440cbdcf3877.mp3",
  "What operation makes this correct? Seven hundred and twenty-three, question mark, four hundred and sixty-eight equals two hundred and fifty-five. Is it plus or minus?": "/assets/audio/audio_q093_b29fc0233885.mp3",
  "What operation makes this correct? Four hundred and eighty-six, question mark, three hundred and fifty-seven equals eight hundred and forty-three. Is it plus or minus?": "/assets/audio/audio_q094_a4f9391c050c.mp3",
  "What operation makes this correct? Six hundred and twelve, question mark, two hundred and seventy-eight equals three hundred and thirty-four. Is it plus or minus?": "/assets/audio/audio_q095_c3cc2a413a0c.mp3",
  "What operation makes this correct? Two hundred and ninety-seven, question mark, four hundred and eighty-five equals seven hundred and eighty-two. Is it plus or minus?": "/assets/audio/audio_q096_63d2b5a4b1b1.mp3",
  "What operation makes this correct? Eight hundred and thirty-four, question mark, four hundred and seventy-nine equals three hundred and fifty-five. Is it plus or minus?": "/assets/audio/audio_q097_6c9af174f124.mp3",
  "What operation makes this correct? Three hundred and seventy-eight, question mark, two hundred and eighty-six equals six hundred and sixty-four. Is it plus or minus?": "/assets/audio/audio_q098_d5e4e3fa218a.mp3",
  "What operation makes this correct? Eight hundred, question mark, three hundred and fifty-six equals four hundred and forty-four. Is it plus or minus?": "/assets/audio/audio_q099_3ea561e34f4f.mp3",
  "What operation makes this correct? Five hundred and sixty-eight, question mark, two hundred and ninety-seven equals eight hundred and sixty-five. Is it plus or minus?": "/assets/audio/audio_q100_1672980b76da.mp3"
};
